### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by andrewclavin** [TheLuomamr/unit-4-game.github.io#1]
HTML looks almost impeccable, What you have wrapped in your p tags isn't really a paragraph, it can just be text in a div or wherever, and this is the uncommon proper usage of a <br> but you should only use one and then add line height in css if you want more space.

Your css is fine, it has some inconsistent spacing though, please be careful to keep it consistent. Nice usage of object-fit.

Your javascript was pretty good, straightforward and easy to follow, but you did have some inconsistent spacing, javascript can quickly become very confusing if you don't have things properly aligned. Also all variables at the top of the block of scope they are declared in before you do any application logic. Lastly you have 4 functions for the clicks that do very similar things, best to take out the things that aren't the same as parameters the function takes and then use the same function for all 4. Very good job, keep up the good work.

Oh, and with README files, don't leave them empty. You can just put the instructions for the homework in there or any thoughts or comments you had about it, a to do list, whatever you want regarding the code in the repo, just don't leave it blank!

**Comment by andrewclavin** [comment]
Oh, and try to put a few comments here and there to explain your code, even when it's fairly straightforward.

**Comment by TheLuomamr** [comment]
Thanks Andrew!
